name: Check Issues

on:
  issues:
    types: [opened]
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - if: contains(github.event.issue.body, '最新版' ) 
        id: close-latest-version
        name: Close Issue(template)
        uses: peter-evans/close-issue@v3
        with:
          comment: 我不知道什么是最新版捏，具体版本号pls
